name: CI
on: push
jobs:
  base:
    name: Base steps
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Whitespace
      run: git diff --check -- HEAD~1
  rspec:
    needs: base
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [2.1, 2.3, 2.4, 2.5, 2.6, 2.7, '3.0', 3.1, 3.2, head, jruby, jruby-head, truffleruby, truffleruby-head]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # 'ruby/setup-ruby' action provides built-in caching
    - name: Run tests (ruby-${{ matrix.ruby-version }})
      run: bundle exec rspec
    - name: Upload coverage
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: coverage-${{ matrix.ruby-version }}
        path: coverage/
