name: CI
on: push
jobs:
  base:
    name: Base steps
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Whitespace
      run: git diff --check -- HEAD~1
  rspec:
    needs: base
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [2.1, 2.3, 2.4, 2.5, 2.6, 2.7, jruby]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # 'ruby/setup-ruby' action provides built-in caching
    - name: Run tests (ruby-${{ matrix.ruby-version }})
      run: bundle exec rspec
